### ISSUE TITLE
What does this really do?

### ISSUE THREAD

**Issue by edwinyzh** [marcelojaloto/SwagDoc#1]
Hi,

Can you explain a little bit on the purpose and usage of this project? 

From where does it get the REST API info? Can it generate the so-called API doc for a [mORMot](https://github.com/synopse/mORMot)-powered REST web server? Thanks.

**Comment by marcelojaloto** [comment]
Hi,

Now in the SwagDoc readme is best described its purpose and use of the project.

https://github.com/marcelojaloto/SwagDoc

The data in your REST API must be automatically collected from your REST server or you can also do it manually, which is not very recommended. In possession of the data, you need to popularize the attributes of the SwagDoc classes.

Yes, it is possible to generate documentation for a REST server regardless of the technology used. What can vary is the level of complexity to collect information from your REST API.

Sorry for the delay in answering you. I needed to be away for a while, but now I'm back.

Bye,
Marcelo Jaloto

**Comment by edwinyzh** [comment]
Thanks @marcelojaloto, I can understand what it does now. So I wanted to see how it's supposed to actually generate the swagger.json file, but it can't be compiled under xe4.

What's the needed Delphi version? Thanks.

**Comment by marcelojaloto** [comment]
Delphi 10.2 Tokyo

**Comment by marcelojaloto** [comment]
@edwinyzh,
an example will be posted shortly. I believe until the end of next week.
