### ISSUE TITLE
general comment / suggestion

### ISSUE THREAD

**Issue by thetoolwiz** [marcelojaloto/SwagDoc#16]
I've been messing around with the GenerateUnitFileForMVCFramework. It looks like it uses the MVC Framework mostly for support of things like attributes, I'd like the part that generates the final .pas unit to incorporate the ability to add further code-gen mechanisms to fill in the contents of the swagger class methods before it spits out the entire unit.

**Comment by marcelojaloto** [comment]
@thetoolwiz this feature was incorporated into the DMVC.
