### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by danieleteti** [marcelojaloto/SwagDoc#2]
I'm the lead developer of delphimvcframework, and I'd like to add swagger support to the APIs offered by the controllers. Could you add some samples about this project so that we can evaluate It?
Thank you

**Comment by marcelojaloto** [comment]
Hello Danielle,

I'm happy with your interesting in SwagDoc library.

I'm on vacation to 26 march.

After my priority is to create documentation and samples for SwagDoc.

The SwagDoc creates swagger.json file  to be copied together with the Swagger files web page. 

The Swagger files can to be in www.swagger.io website.

Do you know swagger documentation version 2.0? This is very important you to know or to learn.

Sorry for my vacation. I can't to help you more fast. 

Marcelo Jaloto

**Comment by marcelojaloto** [comment]
*Download Swagger Interface files 
https://swagger.io/docs/swagger-tools/#download-33

*Documentation Swagger version 2.0
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by marcelojaloto** [comment]
Hello Danielle,

I'm happy with your interesting in SwagDoc library.

I'm on vacation to 26 march.

After my priority is to create documentation and samples for SwagDoc.

The SwagDoc creates swagger.json file to be copied together with the
Swagger files web page.

Visit about Swagger in the  website address www.swagger.io

*Download Swagger Interface files
https://swagger.io/docs/swagger-tools/#download-33

*Documentation Swagger version 2.0
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

Do you know swagger documentation version 2.0? This is very important you
to know or to learn.

Sorry for my vacation. I can't to help you more fast.

Marcelo Jaloto


Em qua, 21 de mar de 2018 21:46, Daniele Teti <notifications@github.com>
escreveu:

**Comment by marcelojaloto** [comment]
@danieleteti 
look at the news, new samples and update in readme.

Do you need more samples?

**Comment by marcelojaloto** [comment]
@danieleteti,
a new full sample is available!

[Download here!](https://github.com/marcelojaloto/SwagDoc/tree/master/Demos/SampleApi)

![image](https://user-images.githubusercontent.com/20048296/46588904-c6cd5880-ca79-11e8-8a8a-ec38ba7ff95a.png)

**Comment by danieleteti** [comment]
Thank you @marcelojaloto
We'll try to integrate it before the upcoming ITDevCon9. 
Thank you for the notification.

**Comment by ghost** [comment]
@danieleteti, 

it's a great pleasure to have SwagDoc embedded in your framework, and even more to have an ITDevCon9 mentioned spec.

I'm going to present SwagDoc on October 23 at the Embarcadero Conference 2018 here in Brazil.

When you can, please keep me informed of the progress of your integration between Delphi MVC Framework and SwagDoc.

Thank you!
